### ISSUE TITLE
requirements not updated

### ISSUE THREAD

**Issue by yodahuang** [susanxie123/flappy-bird-for-fbb#1]
`requirements.txt` is stale. I suggest using tools such as (https://github.com/bndr/pipreqs)[pipreqs] to do so.

**Comment by susanxie123** [comment]
Looks like the only advantage of pipreqs over pip freeze is to note packages not installed by pip. I actually don't like that to happen and that's why I use virtualenv. I didn't upload requiements.txt because it's still empty. :)
